# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2a971b615a3d04a7fea5789c6130b147c84a48fe08396b63656958c70c56c5abb1233b1cfc74a38085bd239605a4c520b3609595a2b9a50721f3dc1d595ef86

test:
  secret_key_base: c622ccfa1a5678d03afceb4fada5aae99a135ff735df01bb4b5558d2c3e44eea22524a3c6c61d33386fdd83f69859139e2d30281eae6dd2a74e499f7fbc59a3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
